# Generated by Django 4.0 on 2024-01-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('strawberry', models.FloatField()),
                ('apricot', models.FloatField()),
                ('cointerau', models.FloatField()),
                ('almond', models.FloatField()),
                ('sour_cream', models.FloatField()),
                ('vanilla', models.FloatField()),
                ('grapefruit', models.FloatField()),
            ],
        ),
    ]
