# Generated by Django 4.0 on 2024-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0002_rename_sour_cream_ingredients_milk_chocolate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(default='Ingredients', max_length=100),
        ),
    ]
