# Generated by Django 4.0 on 2024-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0003_alter_ingredients_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(default='Ingredients', max_length=100, primary_key=True, serialize=False),
        ),
    ]
