# Generated by Django 4.0 on 2024-02-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0004_remove_ingredients_id_alter_ingredients_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='water',
            field=models.FloatField(default=0),
        ),
    ]
