# Generated by Django 4.0 on 2024-02-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0005_ingredients_fat_ingredients_sugar_ingredients_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients_Recipe',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('water', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='water',
        ),
    ]
