# Generated by Django 4.0 on 2024-02-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0009_ingredients_pair_0_ingredients_pair_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='pair_0',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_10',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_11',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_12',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_13',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_14',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_15',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_16',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_17',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_18',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_19',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_7',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_8',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pair_9',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
