# Generated by Django 4.0 on 2024-02-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bake', '0010_alter_ingredients_pair_0_alter_ingredients_pair_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='pair_20',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_21',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_22',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_23',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_24',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_25',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_26',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_27',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_28',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_29',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_30',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_31',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_32',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_33',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_34',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_35',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_36',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_37',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_38',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='pair_39',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
